name: Jianges Tests
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    paths:
      - examples/**
  pull_request:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        directory: [
          basic-mini,
          basic,
          chrome-for-testing,
          chromium,
          firefox-esr,
          included-as-non-root
          ]
        os: [
          ubuntu-24.04-arm  # testing Linux/arm64 platform
          ]
        exclude:
          - os: ubuntu-24.04-arm
            directory: chrome-for-testing #browser not available for Linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Enable debug logging
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Reinstall Docker
        run: |
          ps aux | grep systemd
          sudo systemctl daemon-reexec
          sudo ls -l /var/run/docker.sock
          sudo apt-get install docker.io
        continue-on-error: true
      - uses: actions/checkout@v4
        continue-on-error: true
      - name: Check docker status
        run: sudo systemctl status docker
        continue-on-error: true
      - name: Start Docker in case it's not running on arm VMs
        run: sudo systemctl start docker
        continue-on-error: true
      - name: Restart Docker
        run: |
          sudo systemctl restart docker
          sudo killall -9 dockerd
          sudo /usr/local/share/docker-init.sh
        continue-on-error: true
      - name: Check docker.service status
        run: sudo systemctl status docker.service
        continue-on-error: true
      - name: Run test script
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: re-run test script
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
