name: npm ci
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    paths:
      - examples/**
  pull_request:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        directory: [
          basic-mini,
          basic,
          chrome-for-testing,
          chromium,
          firefox-esr,
          included-as-non-root
          ]
        os: [
          ubuntu-24.04-arm  # testing Linux/arm64 platform
          ]
        exclude:
          - os: ubuntu-24.04-arm
            directory: chrome-for-testing #browser not available for Linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: where is npm
        run: whereis npm
      
      - uses: actions/checkout@v4
      - name: Run test script
        working-directory: examples/${{ matrix.directory }}
        run: npm ci

      - name: chown
        if: failure()
        run: sudo chown -R runner:runner /var/log* /var/lib/systemd
        
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: logs-${{ matrix.directory }}-${{ matrix.os }}
          path: |
            .
            /var/lib/systemd/coredump
            /var/log*
